In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('preprocessed_hotel 수정.csv')

In [8]:
df.drop('date_pair', axis=1, inplace=True)

In [10]:
df

,hotel_name,region,ratings,price,start_date,end_date,capacity,new_region,금전 상황
0,플레이스 캠프 제주,"성산읍, 서귀포",4.05,51146,2023-07-24,2023-07-25,1,성산읍,자린고비
1,호텔 케니 서귀포,"서귀포시, 서귀포",4.05,37909,2023-07-24,2023-07-25,1,서귀포시,자린고비
2,타마라 제주 호텔,"서귀포시, 서귀포",4.10,34422,2023-07-24,2023-07-25,1,서귀포시,자린고비
3,켄싱턴리조트 서귀포,서귀포,3.65,259015,2023-07-24,2023-07-25,1,서귀포,욜로
4,라마다 제주시티호텔,"제주 시내, 제주",4.00,96512,2023-07-24,2023-07-25,1,제주시,평범
...,...,...,...,...,...,...,...,...,...
157347,구덕 게스트하우스,"서귀포시, 서귀포",4.35,958769,2023-07-24,2023-08-25,4,서귀포시,자린고비
157348,호텔 통 연동 제주,"제주 시내, 제주",3.30,1238400,2023-07-24,2023-08-25,4,제주시,자린고비
157349,HY 초이 호스텔,"서귀포시, 서귀포",4.00,1440371,2023-07-24,2023-08-25,4,서귀포시,가성비
157350,파밀리아호텔,서귀포,4.25,3035109,2023-07-24,2023-08-25,4,서귀포,욜로
157351,간드락 게스트 하우스,"제주 시내, 제주",4.30,584800,2023-07-24,2023-08-25,4,제주시,자린고비

In [11]:
df['start_date'] = pd.to_datetime(df['start_date'])
df['end_date'] = pd.to_datetime(df['end_date'])

In [12]:
df['start_date'] = df['start_date'].dt.strftime('%Y-%m-%d %H:%M:%S')
df['end_date'] = df['end_date'].dt.strftime('%Y-%m-%d %H:%M:%S')

In [14]:
df.to_csv('preprocessed_hotel 수정.csv', index=False)

In [15]:
df2 = pd.read_csv('preprocessed_cars 수정.csv')

In [16]:
df2

,car_name,brand_name,seats,size,fuel_type,transmission_type,rental_company_name,age_req,driving_experience,year,ratings,num_ratings,price,start_date,end_date,금전 상황
0,그랜드스타렉스12인승,현대,12,승합,경유,오토,다움렌트카,26,1,19,3.7,10,15000,2023-07-21,2023-07-22,자린고비
1,그랜드스타렉스12인승,현대,12,승합,경유,오토,굿모닝렌트카,26,2,18~19,3.4,3,23500,2023-07-21,2023-07-22,자린고비
2,그랜드스타렉스12인승,현대,12,승합,경유,오토,로그인렌트카,26,2,20,3.6,11,25100,2023-07-21,2023-07-22,자린고비
3,그랜드스타렉스12인승,현대,12,승합,경유,오토,무지개렌트카,26,2,18~20,4.4,15,29100,2023-07-21,2023-07-22,가성비
4,그랜드스타렉스12인승,현대,12,승합,경유,오토,퍼스트렌트카,26,1,19,4.8,6,32600,2023-07-21,2023-07-22,가성비
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137500,제네시스 G90(4WD),현대,5,고급,휘발유,오토,제주OK렌터카,26,1,20,4.2,8,296000,2023-08-18,2023-08-19,플렉스
137501,카니발 하이리무진 7인승,기아,7,승합,경유,오토,땡큐제주렌트카,26,3,21,4.8,5,306000,2023-08-18,2023-08-19,플렉스
137502,[수입]22 BMW 420컨버터블,BMW,4,수입,휘발유,오토,제주OK렌터카,26,1,22,4.2,8,341800,2023-08-18,2023-08-19,플렉스
137503,(캠핑카)코지 560,기아,5,승합,경유,오토,더세븐렌트카,30,2,22,0.0,0,475200,2023-08-18,2023-08-19,플렉스
137504,(캠핑카)포레스트,현대,4,승합,경유,오토,더세븐렌트카,30,2,22,0.0,0,514800,2023-08-18,2023-08-19,플렉스

In [17]:
df2['start_date'] = pd.to_datetime(df2['start_date'])
df2['end_date'] = pd.to_datetime(df2['end_date'])

In [18]:
df2['start_date'] = df2['start_date'].dt.strftime('%Y-%m-%d %H:%M:%S')
df2['end_date'] = df2['end_date'].dt.strftime('%Y-%m-%d %H:%M:%S')

In [19]:
df2

,car_name,brand_name,seats,size,fuel_type,transmission_type,rental_company_name,age_req,driving_experience,year,ratings,num_ratings,price,start_date,end_date,금전 상황
0,그랜드스타렉스12인승,현대,12,승합,경유,오토,다움렌트카,26,1,19,3.7,10,15000,2023-07-21 00:00:00,2023-07-22 00:00:00,자린고비
1,그랜드스타렉스12인승,현대,12,승합,경유,오토,굿모닝렌트카,26,2,18~19,3.4,3,23500,2023-07-21 00:00:00,2023-07-22 00:00:00,자린고비
2,그랜드스타렉스12인승,현대,12,승합,경유,오토,로그인렌트카,26,2,20,3.6,11,25100,2023-07-21 00:00:00,2023-07-22 00:00:00,자린고비
3,그랜드스타렉스12인승,현대,12,승합,경유,오토,무지개렌트카,26,2,18~20,4.4,15,29100,2023-07-21 00:00:00,2023-07-22 00:00:00,가성비
4,그랜드스타렉스12인승,현대,12,승합,경유,오토,퍼스트렌트카,26,1,19,4.8,6,32600,2023-07-21 00:00:00,2023-07-22 00:00:00,가성비
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137500,제네시스 G90(4WD),현대,5,고급,휘발유,오토,제주OK렌터카,26,1,20,4.2,8,296000,2023-08-18 00:00:00,2023-08-19 00:00:00,플렉스
137501,카니발 하이리무진 7인승,기아,7,승합,경유,오토,땡큐제주렌트카,26,3,21,4.8,5,306000,2023-08-18 00:00:00,2023-08-19 00:00:00,플렉스
137502,[수입]22 BMW 420컨버터블,BMW,4,수입,휘발유,오토,제주OK렌터카,26,1,22,4.2,8,341800,2023-08-18 00:00:00,2023-08-19 00:00:00,플렉스
137503,(캠핑카)코지 560,기아,5,승합,경유,오토,더세븐렌트카,30,2,22,0.0,0,475200,2023-08-18 00:00:00,2023-08-19 00:00:00,플렉스
137504,(캠핑카)포레스트,현대,4,승합,경유,오토,더세븐렌트카,30,2,22,0.0,0,514800,2023-08-18 00:00:00,2023-08-19 00:00:00,플렉스

In [21]:
df2.to_csv('preprocessed_cars 수정.csv', index=False)